### ISSUE TITLE
Provide a way to list locally available providers

### ISSUE THREAD

**Issue by ncoghlan** [projectatomic/atomicapp#107]
atomicapp doesn't currently provide a way to easily check which providers are at least nominally available locally. A command like `atomicapp list-providers` could help indicate which provides are installed *and* have their dependencies met (e.g. kubectl CLI for the kubernetes provider).

**Comment by aweiteka** [comment]
We *should* be failing gracefully if the provider is not available. See https://github.com/projectatomic/atomicapp/pull/86

**Comment by goern** [comment]
I think #86 implements this (in a different but good way) the use case is like `atomic run <someatomicapp>` and if a provider is not implemented (eg no artifacts for openshift are provided by someatomicapp's vendor), than `atomic run` should fail gracefully. A list of supported providers is highly depending on the vendor of the atomic app as he may or may not provide artifacts.
