### ISSUE TITLE
prevent atomicapp from running the same image twice at the same time

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#119]
We should not run twice, at lease when we merge the REST API feature it will break as port 5000 may be bound by another instance of atomicapp.

**Comment by vpavlin** [comment]
It's a bit confusing from the summary - how does the word "image" relates to this? Otherwise - any ideas how to solve it? Some lock file?

**Comment by vpavlin** [comment]
I'd probably use this: https://pypi.python.org/pypi/lockfile but that would bring another dependency. Any objections, suggestions?:)

**Comment by vpavlin** [comment]
Fixed by #207
