### ISSUE TITLE
support kubernetes namespaces via answers.file 

### ISSUE THREAD

**Issue by sub-mod** [projectatomic/atomicapp#122]
support kubernetes namespaces via answers.file 
so that when create artifacts via kubectl command --namespace <namespace> argument can be used to create artifacts within a namespace.
@vpavlin

**Comment by sub-mod** [comment]
https://github.com/sub-mod/atomicapp/commit/8841c5358fcc1b42786a14d2e26d5a7023ea34d4

**Comment by vpavlin** [comment]
@sub-mod I think this was fixed by #123, correct?

**Comment by sub-mod** [comment]
@vpavlin  yes
