### ISSUE TITLE
implement STOP for OpenShift provider

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#135]
see https://trello.com/c/k14cmfdj

**Comment by goern** [comment]
Think if we can use the OS tooling rather than atomicapp's?!

**Comment by aweiteka** [comment]
Proposal

* `STOP` means to stop the deployment but not remove it.
* `UNINSTALL` means remove/delete/cleanup the deployment.

**Comment by dustymabe** [comment]
@aweiteka you are still assigned to this issue. Does this issue change with the new information around our openshift strategy?

**Comment by aweiteka** [comment]
@dustymabe see comment in #200

**Comment by dustymabe** [comment]
@aweiteka ok, so should we close this issue for now and re-open later?

**Comment by aweiteka** [comment]
Yes.
