### ISSUE TITLE
Running second app in home directory attempts to run wrong app

### ISSUE THREAD

**Issue by nzwulfin** [projectatomic/atomicapp#136]
Platform: Fedora 22 Atomic 22.17

Testing `atomic run projectatomic/helloapache` from Docker Hub, I had issues running a second app after a successful run.  I removed the helloapache pod using kubectl. 

A subsequent run of `atomic run projectatomic/guestbookgo-app` scheduled the 'helloapache' app instead of the 'guestbookgo-app'.

I was running in the 'fedora' home dir, and the artifacts from the 'helloapache' app aren't getting overwritten.  

Going over the `atomic run` output with @vpavlin in #atomic, the relevant output is:

`2015-05-28 17:25:36,331 - atomicapp.install - INFO - App name is projectatomic/guestbookgo-app, will be populated to /atomicapp
2015-05-28 17:25:36,332 - atomicapp.install - INFO - Component data exist in /atomicapp, skipping population...`

fpaste of complete `atomic run` output here http://ur1.ca/mnvxl

Workaround (from @jasonbrooks ): create a new working directory for each new app, and run the `atomic run` command from that new directory.

**Comment by dustymabe** [comment]
@nzwulfin Can you verify that #207 fixed this issue for you and close out this issue if so?

**Comment by dustymabe** [comment]
@nzwulfin nevermind. Looks like your issue really had nothing to do with concurrently running atomic but rather running two different atomicapps back to back without switching your working dir. I think #142 is the real answer here.

**Comment by goern** [comment]
@vpavlin ping?!

**Comment by dustymabe** [comment]
I think this will be taken care of by PR #278. It should be merge shortly and we can confirm before beta-3.
