### ISSUE TITLE
AGPL?

### ISSUE THREAD

**Issue by jzb** [projectatomic/atomicapp#137]
Looking over the repo, I noticed we have gone with the AGPLv3 - which seems an odd, odd choice for something we'd want others to adopt. Can we have a discussion about a more liberal license for this? At least GPL rather than AGPL. Would anyone even be offering Atomic App as a service?

**Comment by goern** [comment]
I am open to anything that keeps our investment into this piece of open source software open and available to us.

**Comment by jasonbrooks** [comment]
It seems that most/many of the other projects in this org are using LGPL.

**Comment by jzb** [comment]
I'd suggest we throw this to atomic-devel and see if there are any objections to LGPL. Note that ASL and other liberal licenses are fairly popular outside our org... while I am good with reciprocal licenses in general, they may hurt us w/adoption. We also need to clarify our contribution policies... that's on me, I'll start working that.

**Comment by goern** [comment]
Thanks!

**Comment by goern** [comment]
@jzb thanks for confirming the feasibility of the change with rfontana!
