### ISSUE TITLE
RFE: generate nulecule snippets from Dockerfile

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#14]
given the fact that we have a Dockerfile, containing LABELs, we could write a little compiler that generated  Nulecule snippets from that Dockerfile

**Comment by vpavlin** [comment]
Could you elaborate a bit more? Which Dockerfile? What LABELs? Which snippets would you like to generate? (I am all for auto-generation of anything, just need more details:) )

**Comment by goern** [comment]
looking at the example http://github.com/goern/atomicapp-spec/blob/feature/example-dockerfile/spec/0.0.2/examples/template/Dockerfile I think that the whole content could be generated from the corresponding https://github.com/goern/atomicapp-spec/blob/feature/example-dockerfile/spec/0.0.2/examples/template/Nulecule 

We should put this autogeneration feature somewhere.

**Comment by vpavlin** [comment]
Yes, it should be possible using the schema and information from the Nulecule

**Comment by goern** [comment]
This seems to be a job for DevAssistant...
