### ISSUE TITLE
Add prompt flag to force prompt for all params

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomicapp#148]
If no answerfile is provided and there are defaults for params the user has no way to override defaults. Add a `--prompt` option so the user can force prompting for all params, even if defaults are provided.

Related to https://github.com/projectatomic/nulecule/commit/877d4be154601a7fe3705c62faf524b3a32df42a

**Comment by vpavlin** [comment]
Sadly, we have no way how to that while using container and `atomic` cli (because we cannnot pass any additional arguments through).

OTOH, while useing `atomicapp` directly, there is parameter `--ask` which should do exactly what you are asking for:

```
parser_run.add_argument("--ask", default=False, action="store_true", help="Ask for params even if the defaul value is provided")
```

**Comment by aweiteka** [comment]
Ah, thanks for the reminder. Once we get support in atomic CLI `--ask` will be exposed. Until then we wait.
