### ISSUE TITLE
refactor test_path (for binaries) to central config/constants file

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#149]
Move definition of search path from https://github.com/markllama/atomicapp/blob/answer-kubectl/atomicapp/providers/kubernetes.py#L51 for example to https://github.com/projectatomic/atomicapp/blob/master/atomicapp/constants.py

Should be done for `os` or `osc` too.

**Comment by vpavlin** [comment]
nope, this is a provider specific information. Constants are global for the whole project

**Comment by aweiteka** [comment]
Close this then?

**Comment by goern** [comment]
ja.
