### ISSUE TITLE
keep version info in one location

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#155]
cant we read what we need at https://github.com/projectatomic/atomicapp/blob/master/setup.py#L44 from https://github.com/projectatomic/atomicapp/blob/master/atomicapp/constants.py#L26 ?

**Comment by LalatenduMohanty** [comment]
@goern @aweiteka this looks like already fixed. Can we close this?

**Comment by goern** [comment]
no, still not fixed.

**Comment by LalatenduMohanty** [comment]
@goern more info required. I can try fixing this.

**Comment by dustymabe** [comment]
@LalatenduMohanty I thihnk @charliedrage had already submitted code that fixed this but it broke something else so he pulled it back out for now. @charliedrage can you confirm and assign this issue to yourself if so?

**Comment by charliedrage** [comment]
@dustymabe yup, I will work on this, previous version borked since I introduced a change to add VERSION to the app directory

**Comment by dustymabe** [comment]
@cdrage did you fix this already?

**Comment by cdrage** [comment]
@dustymabe I tried when I first started work on Atomic App. But it's not really needed anymore since everything is in constants.py

**Comment by aweiteka** [comment]
I think close this.
