### ISSUE TITLE
Atomicapp image "LABEL INSTALL" should prepare to run rather than unpack

### ISSUE THREAD

**Issue by markllama** [projectatomic/atomicapp#159]
The current behavior of "atomic install" with an atomicapp image is to unpack the atomicapp information into the current working directory.

Rather, INSTALL should prepare the container to run on the host, requesting and importing any necessary inputs (creating an answers.conf _inside_ the container.

Then RUN would execute the atomicapp using that configuration.

It is possible that this conflicts with the controls for the atomic command.  We should discuss how atomic is meant to work, and how that is reflected in how atomicapp works.

## workflow

- prepare - dry-run, provide answer file, provide unresolved answers from answer file
  create answer file and pre-run container (image instance)
- start - execute with provided customizations...
- unpack - place image atomicapp configuration in caller's CWD for dev/debug

Terminology needs to be reconciled and documented.

**Comment by aweiteka** [comment]
related to #184

**Comment by dustymabe** [comment]
So we now have `fetch` instead of `install`. This was done in #525. Closing.
