### ISSUE TITLE
Unable to install/run apps

### ISSUE THREAD

**Issue by sub-mod** [projectatomic/atomicapp#163]
I am using the latest code.
I am unable to install any apps. I get the below error. Has anyone come across this issue.
@goern @aweiteka @vpavlin  ?

atomicapp install projectatomic/helloapache
2015-06-25 01:01:49,139 - atomicapp.install - INFO - App name is projectatomic/helloapache, will be populated to None
latest: Pulling from docker.io/projectatomic/helloapache
6941bfcbbfca: Already exists
41459f052977: Already exists
fd44297e2ddb: Already exists
2a5277132780: Already exists
ddfed462f7fc: Already exists
bc2d1adf67f4: Already exists
7ff66010961b: Already exists
31d63f352501: Already exists
099901b20645: Already exists
6cbe2b22df74: Already exists
d5af165ea1a8: Already exists
0265c208363b: Already exists
864ddcb2d58e: Already exists
df46b2bde9b8: Already exists
57fd5eb17cb0: Already exists
4b470bdff1dc: Already exists
dc5b0348b1fe: Already exists
5256bb77be3d: Already exists
ee69329d37be: Already exists
b4de4a097285: Already exists
Digest: sha256:98f997261df96e99f8d21814410d075270a3b0755ae21022eb0b73329c00ac5c
Status: Image is up to date for docker.io/projectatomic/helloapache:latest
ab4d0a4c5cfba86a3d221524afc5c87e0a8a92c0cb7b6a460dd7de7655790a5d
2015-06-25 01:01:56,612 - atomicapp.utils - INFO - Using temporary directory /tmp/nulecule-dN22r3
Error response from daemon: Could not find the file /application-entity in container helloapache-crRxlp
Error response from daemon: Cannot destroy container helloapache-crRxlp: Driver devicemapper failed to remove root filesystem ab4d0a4c5cfba86a3d221524afc5c87e0a8a92c0cb7b6a460dd7de7655790a5d: Device is Busy
Error: failed to remove containers: [helloapache-crRxlp]
2015-06-25 01:02:17,888 - atomicapp.cli.main - ERROR - Exception caught: Exception('Nulecule not found: /tmp/nulecule-dN22r3/application-entity/Nulecule',)
2015-06-25 01:02:17,888 - atomicapp.cli.main - ERROR - Run the command again with -v option to get more information.

**Comment by vpavlin** [comment]
@sub-mod Can you run the `projectatomic/helloapache` like this

```
docker run --name tmp0 -it --rm --entrypoint bash projectatomic/helloapache
```

and see if `/application-entity` contains appropriate files.

This sort of suggests you might have Docker broken on your host

```
Error response from daemon: Could not find the file /application-entity in container helloapache-crRxlp
Error response from daemon: Cannot destroy container helloapache-crRxlp: Driver devicemapper failed to remove root filesystem ab4d0a4c5cfba86a3d221524afc5c87e0a8a92c0cb7b6a460dd7de7655790a5d: Device is Busy
```

**Comment by sub-mod** [comment]
I had to downgrade my docker to get this working
It works now with docker 1.6  but doesnt work with docker 1.7

**Comment by goern** [comment]
What is your OS? And how did you install docker 1.7?

**Comment by sub-mod** [comment]
F22 , yum install docker , then yum update docker.

**Comment by aweiteka** [comment]
@sub-mod is this the same issue as #174? If so can we close this?

**Comment by sub-mod** [comment]
I am closing this issue because i dont see this error anymore and I can't figure out why it happened.
