### ISSUE TITLE
do we need `--net=host` ?

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#165]
The Dockerfiles contain `--net=host`, do we need that or is it just left over from some reorg done by commit db2eeab6038b22f9c01d1515ec15cc2e7d6dce28 ?

**Comment by aweiteka** [comment]
I found we needed this to support making calls to docker. I'm not clear on the technical reason but it failed without it.

**Comment by goern** [comment]
oh, so communication to docker is not don via `/run/docker.sock` ?

**Comment by aweiteka** [comment]
@goern we use the docker API

**Comment by vpavlin** [comment]
I am not sure about issues with Docker, but there was definitely issue with Kubes without `--net=host`

**Comment by goern** [comment]
so the answer is 'yes, for kubernetes provider'
