### ISSUE TITLE
Update All app images in atomicapp dockerhub repo

### ISSUE THREAD

**Issue by sub-mod** [projectatomic/atomicapp#177]
Since the Dockerfile LABELS have changed
Kindly update all apps in the dockerhub.
Also change atomicapp:dev and atomicapp:latest

@goern 
needed for https://github.com/cockpit-project/cockpit/pull/2474

**Comment by vpavlin** [comment]
All Docker Hub repos related to Atomic App are no linked and will be rebuilt on every projectatomic/atomicapp build.

**Comment by vpavlin** [comment]
Although we have triggeres set, all teh app images depend on :0.1.1 tag of atomicapp image so this will be really fixed after we release new version (and update examples)

**Comment by goern** [comment]
@vpavlin cant we close this? all Nulecule examples have been updated. Autobuild of all the atomicapp and its tag is enabled...

**Comment by sub-mod** [comment]
@goern this issue for me to track the pending work for cockpit#2474 
The litmus test for closing this issue is when 
atomic info projectatomic/helloapache
would look like this
STOP         : docker run -it --rm ${OPT1} --privileged -v `pwd`:/atomicapp -v /run:/run -v /:/host --net=host --name ${NAME} -e NAME=${NAME} -e IMAGE=${IMAGE} ${IMAGE} -v ${OPT2} stop ${OPT3} /atomicapp
RUN          : docker run -it --rm ${OPT1} --privileged -v `pwd`:/atomicapp -v /run:/run -v /:/host --net=host --name ${NAME} -e NAME=${NAME} -e IMAGE=${IMAGE} ${IMAGE} -v ${OPT2} run ${OPT3} /atomicapp
INSTALL      : docker run -it --rm ${OPT1} --privileged -v `pwd`:/atomicapp -v /run:/run  --name ${NAME} -e NAME=${NAME} -e IMAGE=${IMAGE} ${IMAGE} -v ${OPT2} install ${OPT3} --destination /atomicapp /applicatio

instead of 
STOP         : docker run -it --rm --privileged --net=host -v `pwd`:/atomicapp -v /run:/run -v /:/host --name NAME -e NAME=NAME -e IMAGE=IMAGE IMAGE -v stop /atomicapp
RUN          : docker run -it --rm --privileged --net=host -v `pwd`:/atomicapp -v /run:/run -v /:/host --name NAME -e NAME=NAME -e IMAGE=IMAGE IMAGE -v run /atomicapp
INSTALL      : docker run --rm -it --privileged -v /run:/run -v `pwd`:/atomicapp -e IMAGE=IMAGE -e NAME=NAME --name NAME IMAGE -v install --destination /atomicapp /application-entity

**Comment by bexelbie** [comment]
Looks like this can't close until we rev the image.  We last released 0.1.1 in May.  Can we do 0.1.2?

**Comment by goern** [comment]
sure, if no objections I will tag and build a 0.1.2 today

**Comment by sub-mod** [comment]
@goern kindly release 0.1.2 with https://github.com/projectatomic/atomicapp/pull/183 as well

**Comment by goern** [comment]
as we are right in the process of syncing atomicapp releases with the CDK release cycle, please use the `projectatomic/atomicapp:dev` image as that equals the master branch.
