### ISSUE TITLE
add random part to name of containers

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#182]
Containers started by atomicapp should carry unique names. This problem is solved to the OpenShift provider, as OpenShift is responsible for generating the names, same applies for the Kubernetes provider. Using the docker provider, an application packager can choose and name (via `--name` of docker command) and this may lead to name collisions and therefore to containers not starting up as expected.

* Either we document a good practice (not use any `--name` within the docker provider) or
* we invent some logic in atomicapp that overwrites any given name with a uuid'ed name

**Comment by bexelbie** [comment]
I believe we should add a unique name generator so that the resulting container remains identifiable as part of the application.  Perhaps we could use something where we start the container, get a docker random name and then `docker rename` the container to application-dockername

**Comment by goern** [comment]
closed by #263
