### ISSUE TITLE
"Install" UX/workflow

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomicapp#184]
We've struggled with what it means to "install" an application and it has created some confusion. I was using Brent Baude's [image-scanner](https://github.com/baude/image-scanner) and liked the installation experience.

```
$ sudo atomic install baude/image-scanner-testing
[sudo] password for aweiteka: 
Trying to pull baude/image-scanner-testing ...
d0ff22101af6: Download complete 
...
90d697877556: Download complete 
Status: Downloaded newer image for baude/image-scanner-testing:latest
docker run --rm -it --privileged -v /etc/:/host/etc/ -e IMAGE=baude/image-scanner-testing -e NAME=image-scanner-testing baude/image-scanner-testing sh /root/image-scanner/docker/image-scanner-install.sh
Creating directory /etc/image-scanner

The image-scanner configuration file is located at /etc/image-scanner/image-scanner.conf with defaults.
```

Two things I like:

1. The user gets information about what has happened and what to do next. He uses [this script](https://github.com/baude/image-scanner/blob/master/docker/image-scanner-install.sh).
2. Install really just means "generate and download configuration file" and it's clear.

I'll add that using current workdir is confusing to people, myself included. We could put that in a tempdir and let users know that it's there.

**Comment by aweiteka** [comment]
Related to https://github.com/projectatomic/atomicapp/issues/142

**Comment by dustymabe** [comment]
As part of the merge 7d4dbab we no longer unpack in cwd and we also give the user a message about where the installed files are that he/she can use that directory to manage the application. Closing this.
