### ISSUE TITLE
document the communication between Atomic App and Cockpit

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#191]

**Comment by sub-mod** [comment]
In Cockpit a click on deploy button would 
1) installs the image via command
ex :  atomic install --opt2="--answers-format=json" submod/guestbookphp-app
The install step would create a answers.conf.sample file which would contain param/values in json format

this json data is shown on the UI for the user to modify/add param_values

2) A second click on deploy button would 
first save the json_data shown on the UI as answers.conf file
and then will run the run command
ex:  atomic run --opt2="--answers=/atomicapp/answers.conf" submod/guestbookphp-app

**Comment by goern** [comment]
will this be part of the cockpit users guide? could you pls write a little about the messages that will be exchanged, how they will be exchanged, where they are defined? what we should not do in the future, which components of cockpit have been coupled to atomic app.

**Comment by aweiteka** [comment]
@sub-mod could you provide an update to this? Since it's a cockpit dependency could you own this task?

**Comment by dustymabe** [comment]
timeout.. closing
