### ISSUE TITLE
have a 'download docker images only' mode which is handy when performing an update

### ISSUE THREAD

**Issue by jstrachan** [projectatomic/atomicapp#20]
if you want to upgrade to a new version of stuff; it can take a while to load new docker images. so its handy to have a 'download docker images only' mode where we iterate through all the kubernetes json (after OpenShift templates are expanded), find all the docker images and do a pull first.

Then if you need to delete pods/RCs, the rollover time is gonna be quite quick since the images are already locally fetched

**Comment by aweiteka** [comment]
I think this is a kubernetes feature. Kubernetes pulls the (updated) images down to each node. If there's a kubectl client call that exposes this behavior then we could implement that.

**Comment by goern** [comment]
this seems to be implemented by now, @jstrachan could you please check `atomic install` should dwym.
