### ISSUE TITLE
Fix pep8 warnings for codebase

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/atomicapp#203]
If ran pep8 coding guidelines checker on code-base, it throws a bunch of warnings.
Idea here is to fix those warnings and have code compliant with pep8 coding guidelines.

**Comment by aweiteka** [comment]
@navidshaikh nice. We should get a PEP8 check in the Travis job.

**Comment by navidshaikh** [comment]
@aweiteka : Yes, a gate for PEP8 check should help.
