### ISSUE TITLE
support rolling upgrades with Kubernetes / OpenShift to allow new versions to be incrementally migrated to

### ISSUE THREAD

**Issue by jstrachan** [projectatomic/atomicapp#21]
when using Kubernetes / OpenShift we can perform rolling upgrades; where essentially new versions of ReplicationControllers can be used and things can gradually be rolled over from the old version to the new version as folks verify the new version works.

So we should be able to use the correct Kubernetes mechanisms to do rolling upgrades nicely. (Maybe using OpenShift DeploymentConfig?)

**Comment by aweiteka** [comment]
We really don't want to re-implement the deployment logic of openshift into kubernetes. OpenShift has this functionality via deployment configs.

**Comment by goern** [comment]
@jstrachan could you please try to generalize the requirements, so that we can put it in the Nulecule Specification and have it avail as a general feature of the providers (at least Kubernetes, OpenShift). Thx!

**Comment by jstrachan** [comment]
Would things like rolling upgrades and autoscaling just be configured in the openshift template? I guess these things are not relevant to the Nulecule spec; they could be delegated to the OpenShift Template / Kubernetes List?

**Comment by goern** [comment]
@jstrachan ja, that I what we think how it should work. if a Nulecule artifacts provides a upgrade strategy, we will deploy it. 
Sounds like we could close thin issue?
