### ISSUE TITLE
License inconsistencies.

### ISSUE THREAD

**Issue by charliedrage** [projectatomic/atomicapp#225]
CONTRIBUTING.md mentions: gpl-3.txt
License on README.md mentions lgpl-3.0.txt

Wouldn't it be easier to simply have a file named LICENSE similar to normal Github conventions on other repos?

**Comment by goern** [comment]
Well, to put a work under the GNU LGPL you need to have two files: lgpl.txt and gpl.txt, Atomic App is licensed under the GNU LGPL, CONTRIBUTING carries a reference to 'how to put a copyright notice on your file' and that is described in detail in the gpl.txt file. its not inconsistent, just complicated :/

The LICENSE file github provides is exactly the same as lgpl-3.0.txt, therefor it references the GNU GPL too, without placing the gpl-3.0.txt into the repository.
