### ISSUE TITLE
Missing atomicapp-?.?-py?.?.egg-info

### ISSUE THREAD

**Issue by ingvagabund** [projectatomic/atomicapp#228]
When building atomicapp-0.1.3 in Fedora, I am getting the following error:
RPM build errors:
     File not found: /builddir/build/BUILDROOT/atomicapp-0.1.3-1.fc24.noarch/usr/lib/python2.7/site-packages/atomicapp-?.?-py?.?.egg-info

With atomicapp-0.1.1 there was no such error. Atomicapp-0.1.2 suffers the same error.

**Comment by charliedrage** [comment]
@ingvagabund are you able to post the specific build command you used? when you say build do you mean the docker build? or python setup.py install ?

**Comment by ingvagabund** [comment]
%{__python2} setup.py install --skip-build --root %{buildroot}

**Comment by ingvagabund** [comment]
http://pkgs.fedoraproject.org/cgit/atomicapp.git/tree/atomicapp.spec, line 31

**Comment by goern** [comment]
@ingvagabund pls update the version included in the spec file to 0.1.3

**Comment by ingvagabund** [comment]
Updated. The link stays the same.
Spec: http://pkgs.fedoraproject.org/cgit/atomicapp.git/tree/atomicapp.spec
Koji build: http://koji.fedoraproject.org/koji/taskinfo?taskID=10855005
build.log: https://kojipkgs.fedoraproject.org//work/tasks/5006/10855006/build.log

**Comment by navidshaikh** [comment]
I am not really sure if its among accepted practice but modifying egg-info section in `%files` as
```
# egg-info
%{python2_sitelib}/atomicapp*py*egg-info
```
gave me a successful build <http://cbs.centos.org/koji/taskinfo?taskID=29266>

**Comment by dustymabe** [comment]
@ingvagabund looks like the files included in @navidshaikh's rpm are:

```
/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg-info
/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg-info/PKG-INFO
/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg-info/SOURCES.txt
/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg-info/dependency_links.txt
/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg-info/entry_points.txt
/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg-info/requires.txt
/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg-info/top_level.txt
```

Does that mean `%{python2_sitelib}/atomicapp-?.?.?-py?.?.egg-info` should work?

**Comment by ingvagabund** [comment]
That is true. atomicapp-0.1.1 generated atomicapp-0.1-py2.7.egg-info directory. atomicapp-0.1.3 now generates atomicapp-0.1.9-py2.7.egg-info directory. Which I did not noticed and I was listing all generated files. Thanks @navidshaikh. [1] states "*.egg-info files or directories" are supposed to be included. It does not state any limitation on the regular expression.

@dustymabe Should not be atomicapp-0.1.9-py2.7.egg-info name generated with 0.1.3 instead of 0.1.9?

[1] https://fedoraproject.org/wiki/Packaging:Python#Files_to_include

**Comment by dustymabe** [comment]
@ingvagabund This is because in 0.1.3 the value was hardcoded [1] and it was wrong. It has since been fixed.

https://github.com/projectatomic/atomicapp/blob/0.1.3/setup.py#L44

**Comment by ingvagabund** [comment]
Thanks everyone.
