### ISSUE TITLE
remove shebang?

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#238]
@vpavlin could you have a look at http://pkgs.fedoraproject.org/cgit/atomicapp.git/tree/remove-shebang-from-nonexecutable-scripts.patch and figure out why we dont integrate it in here?

**Comment by vpavlin** [comment]
Because then this https://github.com/projectatomic/atomicapp#developers wouldn't work. OTOH it could probably be easily fixed by changing 

```
alias atomicapp="`pwd`/atomicapp/cli/main.py"
```

to

```
alias atomicapp="python `pwd`/atomicapp/cli/main.py"
```
