### ISSUE TITLE
identify non python dependencies

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#247]
we need to identify all non python dependencies we have, like atomic, docker, ... so that we can align with the releases by CentOS, RHEL and Fedora.

**Comment by vpavlin** [comment]
### AtomicApp Core:
* Docker

### Providers
* Docker Provider
  * docker installed in the container
* Kubernetes Provider
  * kubectl either in container or in the `/host`
  * `/etc/kubernetes` either in container or in the `/host`
* OpenShift Provider
  * `oc` either in container oth in the `/host`
  * OpenShift config specified in the `answers.conf`

**Comment by dustymabe** [comment]
Is this taken care of by @vpavlin's comments? Can this be closed or assigned?

**Comment by goern** [comment]
ja, DV, could you figure out if we need to track that RH-internal somewhere or just leave that as part of the doc here?

**Comment by charliedrage** [comment]
@veillard ping

Do we need to update anything upstream / RH-internal for atomicapp requirements?

Have added PR #313 for documentation.

**Comment by charliedrage** [comment]
Requirement docs are merged, I believe that this issue is completed? Should this be closed?

**Comment by dustymabe** [comment]
I think this is done @goern ?

**Comment by goern** [comment]
closed by #313

**Comment by goern** [comment]
closed by #313
