### ISSUE TITLE
Add a `USER` in atomicapp image

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/atomicapp#252]
If no user is set in image the default user is `root`, IMO we need to configure user other than `root`. I propose we use user `atomicapp`.

**Comment by goern** [comment]
ja, we should think about it, open a feature request via an issue, give a short rational why we should do that. (maybe) sync on what `atomic` guys think about it, figure out if we have a std used for that on RHEL and CentOS, if not figure out how to propose a std used for Atomic App on RHEL and CentOS. ... please, thanks!

**Comment by vpavlin** [comment]
How can non-root user run docker commands? (Especially from a container withou being able to run it with `sudo`)

**Comment by goern** [comment]
ja, could involve a pretty deep chain of changes/proposals....

**Comment by TomasTomecek** [comment]
> IMO we need to configure user other than `root`

Why?

Since you are accessing docker daemon, you don't have much options here. User namespaces will help here a lot -- `root` in container would become `arbitrary_user_with_no_privileges` on host.

**Comment by aweiteka** [comment]
> User namespaces will help here a lot -- root in container would become arbitrary_user_with_no_privileges on host.

@TomasTomecek yes, that would be great. Do you have a sense when this feature will land?

This brings up an issue I've been considering: running an atomicapp from within OpenShift will be difficult to test due to root user not being allowed by default. See https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-specific-guidelines  There are some workarounds. We can discuss in another issue.

**Comment by TomasTomecek** [comment]
@aweiteka 
Looks like user namespaces could land into 1.9 https://github.com/docker/docker/issues/15187 https://github.com/docker/docker/pull/12648

> This brings up an issue I've been considering: running an atomicapp from within OpenShift will be difficult to test due to root user not being allowed by default.

I didn't know that. I guess that you can use custom build strategy for now.

**Comment by aweiteka** [comment]
This has become a requirement for OpenShift running atomicapp natively. Here's how I think we can make this work:

1. Add `USER atomicapp` (or whatever--OpenShift prefers numbered users. See [documentation](https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-specific-guidelines))
1. When running in OpenShift it will run as that user
1. Add docker run option `--user=root` to CMD and/or INSTALL|RUN|STOP LABELs.

**Comment by dustymabe** [comment]
needed for openshift work

**Comment by dustymabe** [comment]
Closing.. Not needed for now. The openshift integration work done in #454 doesn't require this.
