### ISSUE TITLE
Refactor  respective  (and add more) tests in separate classes

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/atomicapp#257]
Following up from <https://github.com/projectatomic/atomicapp/pull/254#issuecomment-137357932>
creating a new issue.

Separate respective tests and fix the ordering constraints for the present set of tests.

**Comment by charliedrage** [comment]
Relates to #275

Refractors tests into separate folders + classes. Ex. Gitlab CLI deployment test

**Comment by dustymabe** [comment]
@cdrage @rtnpro @navidshaikh what is the status of this?

**Comment by cdrage** [comment]
@dustymabe It's done, we separated the respective tests to different folders and added a multitude of new tests.
