### ISSUE TITLE
PROPOSAL: atomicapp stop method to docker provider && changes to atomicapp naming conventions

### ISSUE THREAD

**Issue by charliedrage** [projectatomic/atomicapp#264]
See _PULL REQUEST_ for awesomeness!: #263

This PR implements atomicapp stop to the `docker.py` provider as well as propose changes to atomicapp deployment naming conventions.

# Problem statement
Currently, you cannot perform `atomicapp stop` to Docker containers deployed by atomicapp. In order for atomicapp to detect what has or hasn't been deployed, I am proposing a change to the __CONTAINER__ naming conventions in order to be able to easily identify what has or hasn't been deployed by atomicapp.

Currently this PR DOES NOT change the naming conventions currently used by the kubernetes provider, as atomicapp uses the `namespace` param within answers.conf in order to tag each deployment as a whole on kubernetes. HOWEVER in the future, by enforcing a standardized naming convention with the namespace param (atomic_NAME_HASHVALUE) to the kubernetes provider, atomicapp will be able to detect and  more safely remove kubernetes deployments.

# Changes

In order to implement this change, there are two proposals:
  1. Each Docker container will be named according to a specified naming convention atomic_NAME_HASHVALUE
    - Each hashvalue will be calculated via a 12 character UUID generated by Python
  2. It is advised to avoid using '--name' within the atomicapp `artifacts/docker/` files and instead using the namespace param in `answers.conf`, but not enforced

# Opportunity
This opens up the opportunity to be able to detect and stop other container providers such as __runc__ and __rkt__ by utilizing ID names (rkt) as well as labels (runc) with our naming convention

Because each deployment will be __tagged__, this also opens up the opportunity to add `atomicapp ps` to be able to list what has been deployed, what provider it is using, as well as what host.

```bash
#> atomic ps
  Name                          | Provider    |  Host
  ----------------------------------------------------------
  atomic_mariadb_a901230a       |    k8s      |  local
  atomic_helloapache_k901230a   |    docker   |  10.0.0.1
  atomic_mysql_po123039a        |    docker   |  10.0.0.1
  atomic_gitlab_zlk1203a        |    rkt      |  10.0.10.4
```

# Running example

`answers.conf`
```
[helloapache-app]
image = centos/httpd
hostport = 80
[general]
namespace = awesomeapp
provider = kubernetes
```

`atomicapp -v run --provider=docker projectatomic/helloapache`
```
...
2015-09-09 13:19:39,690 - atomicapp.nulecule_base - DEBUG - Param provider already in general with value kubernetes
2015-09-09 13:19:39,690 - atomicapp.nulecule_base - DEBUG - Param namespace already in general with value awesomeapp
2015-09-09 13:19:39,690 - atomicapp.run - DEBUG - Config: {u'image': u'centos/httpd', u'provider': u'kubernetes', u'namespace': u'awesomeapp', u'hostport': 80} 
2015-09-09 13:19:39,690 - atomicapp.run - DEBUG - {u'image': u'centos/httpd', u'provider': u'kubernetes', u'namespace': u'awesomeapp', u'hostport': 80}
2015-09-09 13:19:39,690 - atomicapp.plugin - DEBUG - Writing artifact to /home/wikus/helloapache/.workdir/helloapache-app/artifacts/docker/hello-apache-pod_run
2015-09-09 13:19:39,691 - docker - DEBUG - Given config: {u'image': u'centos/httpd', u'provider': u'kubernetes', u'namespace': u'awesomeapp', u'hostport': 80}
2015-09-09 13:19:39,691 - docker - DEBUG - DEFAULT NAMESPACE: awesomeapp
2015-09-09 13:19:39,707 - docker - INFO - Deploying to provider: Docker
c33649a0eb24f946e91b7c4e8ede4030cd1701a81f41bb604a28db7ee5e57db4
```

`docker ps`
```
▶ docker ps
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS              PORTS                NAMES
c33649a0eb24        centos/httpd           "/run-httpd.sh"        24 seconds ago      Up 22 seconds       0.0.0.0:80->80/tcp   atomic_awesomeapp_c02e836b811c   
```

`atomicapp -v stop --provider=docker projectatomic/helloapache`
```
...
2015-09-09 13:20:51,796 - atomicapp.run - DEBUG - Config: {u'image': u'centos/httpd', u'provider': u'kubernetes', u'namespace': u'awesomeapp', u'hostport': 80} 
2015-09-09 13:20:51,796 - atomicapp.run - DEBUG - {u'image': u'centos/httpd', u'provider': u'kubernetes', u'namespace': u'awesomeapp', u'hostport': 80}
2015-09-09 13:20:51,796 - atomicapp.plugin - DEBUG - Writing artifact to /home/wikus/helloapache/.workdir/helloapache-app/artifacts/docker/hello-apache-pod_run
2015-09-09 13:20:51,797 - docker - DEBUG - Given config: {u'image': u'centos/httpd', u'provider': u'kubernetes', u'namespace': u'awesomeapp', u'hostport': 80}
2015-09-09 13:20:51,797 - docker - DEBUG - DEFAULT NAMESPACE: awesomeapp
2015-09-09 13:20:51,810 - docker - INFO - Undeploying to provider: Docker
2015-09-09 13:20:51,855 - docker - INFO - REMOVING CONTAINER: atomic_awesomeapp_c02e836b811c
atomic_awesomeapp_c02e836b811c
```

`docker ps`
```
▶ docker ps
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS              PORTS               NAMES

```

# Conclusion

If you made it this far, GO TEST IT OUT!
```
git clone https://github.com/charliedrage/atomicapp .
cd atomicapp
sudo python setup.py install
mkdir helloapache && cd helloapache
# optional, install first and edit answers.conf, otherwise the default name is default
# atomicapp -v install --provider=docker projectatomic/helloapache
# mv answers.conf.example answers.conf
# vim answers.conf
atomicapp -v run --provider=docker projectatomic/helloapache
atomicapp -v stop --provider=docker projectatomic/helloapache
```

Let me know what you think in the comments below as well as within the PR #263! Criticisms well encouraged.

EDITED: cleaned up for clearer reading

**Comment by dustymabe** [comment]
Tested this out and things seem to work (at least on the surface). I was able to run helloapache and also change the namespace and port and start another instance of helloapache.

A couple of things that may or may not be related to this:

1. If I run `atomicapp -v stop --provider=docker projectatomic/helloapache` then it still downloads all of the artifacts to the current directory. If we need the artifacts then maybe we should just say "you need the artifacts" rather than downloading them again?
1. I think this is normal (as in kubernetes does this by default) but `docker ps -a` shows the containers still around even with the docker provider. Would it be valuable to have an `atomic remove`?
1. Should we be disallowing running of different applications with the same namespace? Right now if I modify helloapache to use different ports and run two different versions of helloapache then an atomic stop on one of them will stop both of them. I think if we are going to do namespaces then we should disallow re-use of the namespaces so that we don't have collisions like this. If we did this then we could just provide the "namespace" to `atomicapp stop` and maybe stop them that way.

**Comment by charliedrage** [comment]
@dustymabe 

Thanks for the feedback! Here are my thoughts:

1. Because the name of the container may be in the artifacts file (and since we don't have a local build yet: `atomicapp install .`) it relates to point 2 of the change. Should we discourage having names within the artifacts and only keep it in the namespace?

2. Yup. It's normal for now until @aweiteka proposal for adding uninstall is added!

3. You're right. We should add that to the code to prevent removing multiple deployments (if someone deploys with `default` namespace twice, which is bound to happen.

**Comment by dustymabe** [comment]
@charliedrage 

1. I think we should discourage having names within the artifacts. @goern might have a better opinion though.
1. Is uninstall the same thing as remove? I think of uninstall as remove artifacts and images but that doesn't necessarily mean the containers that are no longer running will get cleaned up?
1. Agreed.

**Comment by vpavlin** [comment]
@dustymabe @charliedrage 
1. Yes! I completely agree with discouraging using `--name`, BUT at the same time I would like to strongly discourage us from changing the name if it's already there. I'd like to see a warning saying something like: "Don't use --name, you fool!" :) And maybe even explaining why is it bad, but we definitely shouldn't touch the names which are defined. Here is why...

```
docker run --name my_db db
docker run --name my_webapp --link my_db:db webapp
```

What will happen?

```
Error response from daemon: Could not get container for my_db
```

**Comment by charliedrage** [comment]
@vpavlin you're right, but at the same time isn't linking currently discouraged due to atomicapp not handling artifact ordering and the reason for @rtnpro 's Docker compose request?

**Comment by vpavlin** [comment]
Atomic App does the ordering although not explicitly.

1. go through `graph`
2. is the component external?
  1. create new atomic app, go to 1.
  2. return
3. if the component is not external, run provider

Ordering is there - containers are started as specified in graph and artifacts. But, there is an information disconnection between components.

So linking is not discouraged, it's just very, very fragile:(

**Comment by charliedrage** [comment]
@vpavlin cleaned up the proposal and PR to match what we discussed here + IRC

**Comment by charliedrage** [comment]
Merged :tada:
