### ISSUE TITLE
Allow passing kubeconfig to kubernetes provider

### ISSUE THREAD

**Issue by stefwalter** [projectatomic/atomicapp#266]
Real world kuberenetes is configured with authentication, multi-master, and all sorts of pixie dust. The kubernetes provider should accept a kubeconfig parameter in the ```answers.conf``` to which callers can pass a kubeconfig format file (ie: ```~/.kube/config```) so that kubectl running under atomicapp can find and authenticate against kubernetes.

**Comment by stefwalter** [comment]
https://github.com/projectatomic/atomicapp/blob/master/atomicapp/providers/openshift.py#L58

**Comment by vpavlin** [comment]
The command line option is `--kubeconfig="" ` otherwise the code should be the same as for OpenShift...

Maybe the general option like `providerconfig` in `answers.conf` would make sense
