### ISSUE TITLE
Kubernetes pod never leaves pending state when running mariadb app.

### ISSUE THREAD

**Issue by ggallen** [projectatomic/atomicapp#273]
This should be easy to reproduce.

1. Start kubernetes services.
2. Run "atomic run projectatomic/mariadb-centos7-atomicapp"

After the run the kuberetes pod never leaves the pending state:

    [root@dhcp-41-217 atomic-test]# kubectl get pods
    NAME      READY     STATUS    RESTARTS   AGE
    mariadb   0/1       Pending   0          14m
    [root@dhcp-41-217 atomic-test]# 

There may have been an issue opened about this already, but I have been unable to find it.

You can also reproduce this using the jenkins job https://ci.centos.org/view/AtomicApp/job/mariadb-kubernetes.

**Comment by dustymabe** [comment]
This is most likely the resource issue. The number in this line
https://github.com/projectatomic/nulecule/blob/master/examples/mariadb-centos7-atomicapp/artifacts/kubernetes/mariadb-pod.yaml#L7 should not be 100 but something like 100m.

**Comment by ggallen** [comment]
Changing it to 100m did work.

Now how can this get fixed and packaged so I can pick it up?

**Comment by ggallen** [comment]
Any idea when this fix will be generally available?

**Comment by goern** [comment]
I'll prepare a Atomic App 0.1.10 release on Monday, therefor hold any further merging of pull requests.

@vpavlin @aweiteka
