### ISSUE TITLE
Using the docker python API

### ISSUE THREAD

**Issue by charliedrage** [projectatomic/atomicapp#289]
I am opening this issue to have a discussion about the Docker python API (https://github.com/docker/docker-py)

Should we add this as another library to atomicapp, which would make talking to the localhost Docker easier / more programmatic? Or do we stick to the subprocess commands?

This would help #248 #263 (which was previously discussed) and helped #265

**Comment by dustymabe** [comment]
I would be +1.. but this would be one more external dependency we would carry.

**Comment by charliedrage** [comment]
Going to close this for now and re-open a later date. At the moment there is not enough complexity yet to warrant using the Docker python API.
