### ISSUE TITLE
document the behavior of `atomicapp verbs` and the states an atomicapp may have

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#290]
beautify https://etherpad.mozilla.org/QS0TSJaPhY

**Comment by dustymabe** [comment]
I created https://gist.github.com/dustymabe/2b8920b28561871a256e. I will create a secondary proposal for `status` since I think they can be kept separate.

**Comment by dustymabe** [comment]
This has been documented.. I have opened a PR but we will not merge until after beta-3.
