### ISSUE TITLE
create a restful readonly interface to get params of an Atomicapp

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#30]
As a software doing a deployment of an Atomicapp
I want to query the Atomicall via RESTful http
so that I can learn what parameters are available, required and eventually have default values assigned

**Comment by aweiteka** [comment]
Shouldn't this API go into the [spec](https://github.com/projectatomic/nulecule) then be implemented here?

**Comment by vpavlin** [comment]
In theory, we could define the API in the spec and it's implementation guide, but implementation goes definitely to the tool

**Comment by goern** [comment]
ja, added params api to #89 and closing this.
