### ISSUE TITLE
write a doc on how to write a provider

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#301]
Publish a documentation on how to wirte an Atomic App provider (for example for docker-compose). It should be part of this repository and be published on projectatomic.io/blog

**Comment by dustymabe** [comment]
This is taken care of by https://github.com/projectatomic/atomicapp/pull/383.

**Comment by dustymabe** [comment]
@rtnpro do you want to make a blog post for projectatomic.io ?
