### ISSUE TITLE
Refactor atomicapp command line arguments

### ISSUE THREAD

**Issue by rtnpro** [projectatomic/atomicapp#309]
# Issues
1. ``dry-run`` does not make much sense when used with ``install`` command.
1. ``-a``/``--answers`` does not make sense in case of installing an application, but only during, ``run``. It also does not make much sense in case of ``stop``, as ``stop`` should reuse configuration used during ``run``. 

# Proposed solution
1. ``dry-run`` argument can be moved from ``atomicapp`` command to ``run`` and ``stop`` sub commands.
1. ``-a``/``--answers`` argument can be move to ``atomicapp run`` sub command alone.

Since, these are not major changes and do not require rebuilding atomicapp docker images, I think it will be straight forward to include the fixes in #278

**Comment by vpavlin** [comment]
1. `dry-run` for install was added quite late and it had a reason, though I am not sure what that was and I can't find the issue where it was requested. But I agree, the main value dry-run has is for `run` and `stop`.
2. This is related to https://github.com/projectatomic/atomicapp/pull/278#discussion_r41630905 - currently, yes, answers are not useful for install. I agree we can move it to `run` subcommand.

Second part of 2. is a bit more complicated, but I agree that user shouldn't be need to provide anything for `stop` if he did `run` before.

**Comment by dustymabe** [comment]
@rtnpro considering #332 should we keep this open?

**Comment by dustymabe** [comment]
Closing in favor of the work we are doing in #332.
