### ISSUE TITLE
Proposal: usage of LABELs in Application's Dockerfile

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#33]
To give a little more meaning to the dockerfile and make the meta data available to atomic tool (and other tools like devassistant) I would like to propose the following LABELs

`LABEL io.projectatomic.nulecule.specversion 0.0.2` - this indicates, that the Dockerfile belongs to a Atomicapp, compatible with Nulecule Spec 0.0.2, inferred from that, we know that this docker container is an atomicapp.

**Comment by ncoghlan** [comment]
Related to this, it would be handy if the Dockerfile advertised which providers it supported. For example (suggested by Vaclav):

    LABEL io.projectatomic.nulecule.providers = "kubernetes,docker,openshift"

**Comment by LalatenduMohanty** [comment]
+1 to the idea.
