### ISSUE TITLE
Should ordering matter for options?

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/atomicapp#332]
We have had discussion about our strict ordering for optional arguments: i.e. if it is a global option then it must go before the "verb", if it is a specific option then it must go after the verb. Some of us would rather not have ordering for options, which we think is reasonable as long as the number of global arguments doesn't get to be too many. 

Let's revisit this after beta3.

**Comment by sub-mod** [comment]
+1
strict ordering add restrictions in atomic command
better to remove them

**Comment by rtnpro** [comment]
After doing quite some study (dnf, git commands), and going through argparse, [click](http://click.pocoo.org/5/): a python library for creating command line interfaces, I find that there's no need to fix the issue, as is.

Reasons are:
- Taking as example,  ``git`` CLI. It has multiple command groups, with options at the global level and and at the command group level. It does not let you mix and match the options and args across the root and group levels.
- ``dnf`` has only global options
- ``click`` also does not allow re ordering options across root and group levels.

I do not say that the feature could not implemented, but whatever we do, will be just a hack. And I am not inclined in doing so. Also, I do not see too much benefit out of implementing this feature. All you need is to be a bit systematic when generating atomicapp commands.

However, a solution could be to remove ``global`` options and put all options, explicitly, at the group level.

@dustymabe, @cdrage, what do you say?

**Comment by dustymabe** [comment]
Specifically this merged commit allow for options to go anywhere on the command line: 52bae87
