### ISSUE TITLE
Mesos provider?

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#357]
Has anyone had any experience with Mesos know if it's a viable provider compatible with `atomicapp`?

**Comment by kadel** [comment]
Mesos has a little different architecture then other schedulers, so you need another scheduler (framework) on top of Mesos.
Probably most used one for scheduling Docker containers, and one I have experience with is [Marathon](https://mesosphere.github.io/marathon/).

Marathon has REST API, so it should not be hard to write provider for atomicapp. 
I have plans to look into that, and start working on that.
