### ISSUE TITLE
remove examples from this repository and start curating a 'Atomicapp Examples Repository'

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#38]
As a developer and user of the Nulecule Specification
I want to find one single place on the internet
so that I have a lot of rich examples how to use Nulecule and Atomicapp

**Comment by aweiteka** [comment]
Resolved by https://github.com/projectatomic/atomicapp/commit/9faf5c30035e749e9b7940b58b30f065fc321fca
