### ISSUE TITLE
Extend tests for OpenShift provider

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomicapp#391]
We need provider tests and corresponding examples.

**Comment by aweiteka** [comment]
Should land here: https://github.com/projectatomic/atomicapp/pull/420

**Comment by dustymabe** [comment]
@aweiteka did you mean unit tests?

**Comment by aweiteka** [comment]
@dustymabe yes, unit tests, now tracked in issue #459

**Comment by dustymabe** [comment]
Closing in favor of #459
