### ISSUE TITLE
Disable option to stop from a Nulecule image name

### ISSUE THREAD

**Issue by rtnpro** [projectatomic/atomicapp#396]
In our new workflow, it does not make sense to stop a Nulecule application by it's container image name, neither does the code support that. All, we need to do is update the ``help`` doc for ``app_spec`` for stop command.

**Comment by dustymabe** [comment]
This depends on our integration with atomic cli work. It won't take long to implement. Let's revisit this in a week or two.

**Comment by dustymabe** [comment]
Taking this for now as I need to make a decision on this with regards to atomic CLI + atomicapp for GA.
