### ISSUE TITLE
Bring back install to destination from Nulecule metadata

### ISSUE THREAD

**Issue by rtnpro** [projectatomic/atomicapp#400]
# Problem statement

Let's say, I have a local library of Nulecule apps, cloned from https://github.com/projectatomic/nulecule-library. I'd like to install/run an application from the library in my current working directory or workspace. I would not like to manually copy the metadata to my destination directory in order to use it.

**Comment by dustymabe** [comment]
That would also require us to "know" a location of locally cached apps and automatically look for them. There is just too much magic involved with "detecting" what a user passed and what they actually mean from it. 

Right now the user either passes the name of a container image where the metadata exists or a path to a directory where the metadata already exists (the target directory for the application). Trying to figure out if what they passed in is a src or dst and playing that game really makes the code on the inside harder to understand. 

Do you have suggestions on improving that?
