### ISSUE TITLE
Error when starting the helloapache app

### ISSUE THREAD

**Issue by luebken** [projectatomic/atomicapp#409]
I've build a simple atomic app from `nulecule-library/helloapache`  
```
$ docker build -t mydb-app .
```
When I start atomic via the `projectatomic/atomicapp` image and started it and get this error:
```
$ docker run projectatomic/atomicapp run mydb-app
2015-11-18 15:06:45,055 - atomicapp.plugin - DEBUG - Loading providers from /opt/atomicapp/atomicapp/providers
2015-11-18 15:06:45,065 - atomicapp.nulecule.base - INFO - Unpacking image: mydb-app to /var/lib/atomicapp/mydb-app-5aaea1b301db
2015-11-18 15:06:45,104 - __main__ - ERROR - Command '['/usr/bin/docker', 'version']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/opt/atomicapp/atomicapp/cli/main.py", line 74, in cli_run
    nm.run(**argdict)
  File "/opt/atomicapp/atomicapp/nulecule/main.py", line 182, in run
    self.nulecule = self.unpack(dryrun=dryrun, config=self.answers)
  File "/opt/atomicapp/atomicapp/nulecule/main.py", line 114, in unpack
    nodeps=nodeps, dryrun=dryrun, update=update)
  File "/opt/atomicapp/atomicapp/nulecule/base.py", line 83, in unpack
    docker_handler = DockerHandler(dryrun=dryrun)
  File "/opt/atomicapp/atomicapp/nulecule/container.py", line 34, in __init__
    raise e
CalledProcessError: Command '['/usr/bin/docker', 'version']' returned non-zero exit status 1
```

when I sh into the image to start docker directly I get:
```
$ docker run -ti --entrypoint=/bin/sh projectatomic/atomicapp
sh-4.2# /usr/bin/docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Package Version: docker-1.8.2-7.el7.centos.x86_64
 Go version:   go1.4.2
 Git commit:   bb472f0/1.8.2
 Built:
 OS/Arch:      linux/amd64
Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running? 
```
the version:
```
$ docker run projectatomic/atomicapp -V
2015-11-18 16:20:09,829 - atomicapp.plugin - DEBUG - Loading providers from /opt/atomicapp/atomicapp/providers
atomicapp 0.2.2, Nulecule Specification 0.0.2
```

**Comment by dustymabe** [comment]
@luebken Are you on Fedora 23? This may be your issue: https://bugzilla.redhat.com/show_bug.cgi?id=1278984

**Comment by luebken** [comment]
No I'm on a Mac. ;-)

**Comment by luebken** [comment]
And I get the impression that this whole setup is not working on a Mac. When I go down the `pip install` route described [here](https://github.com/projectatomic/atomicapp#install-this-project) I lots of errors.

**Comment by dustymabe** [comment]
hi @luebken. are you trying to run directly on a mac or inside of a linux virtual machine? We have a vagrant virtualbox box that you can use on a mac if you'd rather try that: https://github.com/projectatomic/adb-atomic-developer-bundle

also, dropb by #nulecule on freenode if you have questions

**Comment by luebken** [comment]
@dustymabe thanks for the pointer. I was trying directly on a Mac with docker-machine and virtualbox. I guess for now a pointer in the [readme](https://github.com/projectatomic/atomicapp/blob/master/README.md) would be great.

As a total Python noob I made some changes and got it running: https://github.com/luebken/atomicapp/tree/mac-fix

Note: This branch is just for documenting my changes it is not really tested nor ready for any merging.

**Comment by rtnpro** [comment]
I think it will be great if we could add some file ``~/.atomicapprc`` where the user can configure how atomicapp runs, e.g., override values in ``contants.py``.

@dustymabe what do you think?

**Comment by dustymabe** [comment]
@rtnpro on initial thought it seems reasonable, but when you think about the fact that we mostly run things in a container this could be kind of hard to pull off and get it right.

**Comment by cdrage** [comment]
Hi @luebken 

I've opened up another issue (#419) in order to discuss OS X compatibility.

**Comment by dustymabe** [comment]
Closing this issue
