### ISSUE TITLE
Is printStatus even used anymore for Cockpit?

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#417]
ping @sub-mod 

Is `printStatus` in `Utils.py` even used anymore for Cockpit?

After a search I found no usage of the function... 

```python
def printStatus(message):
 logger.info("atomicapp.status.info.message=" + str(message))
```

Or did we break it in the new refactor?

**Comment by dustymabe** [comment]
@cdrage most likely we broke it in the refactor. I'll let him comment as well though

**Comment by cdrage** [comment]
I'm going to close this as we've confirmed via @sub-mod + @rtnpro that the new logging implementation works (with the exception of a hack to nulecule.js which will be resolved upstream)
