### ISSUE TITLE
Fix cockpit integration

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#432]
The introduction of our re-factor, broke cockpit integration with logging.

Cockpit uses `atomic` directly. See: https://github.com/cockpit-project/cockpit/blob/master/pkg/kubernetes/nulecule.js

Let's fix this before GA :+1:

**Comment by goern** [comment]
+1 fix it, cockpit is an important part of the story

**Comment by sub-mod** [comment]
depends on https://github.com/projectatomic/atomicapp/pull/415

**Comment by rtnpro** [comment]
@cdrage ping?

**Comment by cdrage** [comment]
ping @sub-mod 
did you get a chance to test this?

**Comment by sub-mod** [comment]
yes, 
I can see the cockpit specific logs.
I might have to add few extra logs in future. So far LGTM.

**Comment by cdrage** [comment]
awesome :+1: :D i'll modify #415 and clean it up a bit before pinging people for review
