### ISSUE TITLE
Support file:// for source inheritence.

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#437]
At the moment we use `docker://` for specifying inherited applications for Atomic App. In the future we should support `file://`, `https://`, `ssh://`, etc.

**Comment by goern** [comment]
so what you say is "Atomic App shall comply to Nulecule Specification 0.0.2 section http://www.projectatomic.io/nulecule/spec/0.0.2/index.html#graphObject" ? ;)

**Comment by cdrage** [comment]
@goern Yes sir!

We'll need to apply this to all URL's in the source :)
