### ISSUE TITLE
 self.nulecule_base.checkAllArtifacts() missing in new refactor.

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#475]
Seems that during the re-factor we've removed a function `checkAllArtifacts()` (correct me if I'm wrong).

Noticed that this was missing when implementing cockpit support for the re factored logging PR

**Comment by cdrage** [comment]
ping @rtnpro

**Comment by rtnpro** [comment]
@cdrage IIRC, yes!

**Comment by cdrage** [comment]
@rtnpro so should we add it back?

**Comment by rtnpro** [comment]
@cdrage Yes!

**Comment by cdrage** [comment]
closing in favour for #545 issue.
