### ISSUE TITLE
atomicapp currently broken with atomic when using dashes in image names.

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#487]
Please see https://github.com/projectatomic/atomic/issues/271

Seems that when using a dash in an image name, it's currently breaking atomicapp functionality.

For example, the image name "wordpress-centos7-atomicapp" doesn't work, while "helloapache"  does when running: `atomic run projectatomic/wordpress-centos7-atomicapp -a answers.conf`

**Comment by dustymabe** [comment]
After trying to recreate this with @cdrage, we could not. Closing
