### ISSUE TITLE
atomicapp should be packaged as a RPM

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/atomicapp#49]
If we get atomicapp as aRPM it will be helpful for maintaining its dependency on other packages and we can bake it in images like Vagrant.

**Comment by goern** [comment]
hmm, a container toolkit should be delivered as a container image, shouldnt it? :)

**Comment by aweiteka** [comment]
We need some work on the README to make this clear, but container packaging is the target.
See https://registry.hub.docker.com/u/projectatomic/atomicapp/

**Comment by whitel** [comment]
Although, it does raise a good point, do we have a recommended way to "get a container" in a kickstart? Can we get a container?

**Comment by goern** [comment]
"get a container"... I guess there is only two ways `docker pull` or `docker import`, while docker import will not maintain the image id (afair). So if you want to preload a Vagrant base box with a docker container image, do a `docker pull` during kickstart...

**Comment by vpavlin** [comment]
Actually you probably mean `docker load` which serves to import existing docker image. `docker import` is used while importing bare rootfs tar(.gz). `docker load` preserves the `id`.

I'd say `docker pull` sounds good for kickstart.

**Comment by vpavlin** [comment]
Atomic App is now packaged as RPM for Fedora https://admin.fedoraproject.org/pkgdb/package/atomicapp/

**Comment by LalatenduMohanty** [comment]
Very nice!

**Comment by veillard** [comment]
Can we have the spec file in git please ?

**Comment by vpavlin** [comment]
@veillard We probably could, but why is that needed? RPM packaging is specific to Fedora/CentOS/RHEL and is not handled by upstream in any way
