### ISSUE TITLE
Atomicapps fails when there is not metadata in Nulecule

### ISSUE THREAD

**Issue by kadel** [projectatomic/atomicapp#502]
AtomicApp fails when there is no `metadata` field in Nulecule.
```
 __main__ - ERROR - __init__() takes at least 6 arguments (7 given)
Traceback (most recent call last):
  File "/opt/atomicapp/atomicapp/cli/main.py", line 98, in cli_run
    nm.run(**argdict)
  File "/opt/atomicapp/atomicapp/nulecule/main.py", line 235, in run
    self.nulecule = self.unpack(dryrun=dryrun, config=self.answers)
  File "/opt/atomicapp/atomicapp/nulecule/main.py", line 139, in unpack
    self.app_path, dryrun=dryrun, config=config)
  File "/opt/atomicapp/atomicapp/nulecule/base.py", line 123, in load_from_path
    namespace=namespace, **nulecule_data)
TypeError: __init__() takes at least 6 arguments (7 given)
```

According to [Nulecule spec](https://github.com/projectatomic/nulecule/tree/master/spec#container-application-object) `metadata` field should be optional.

**Comment by surajssd** [comment]
I would like to work on this issue.

**Comment by dustymabe** [comment]
Suraj, thanks. I assigned the issue to you

**Comment by rtnpro** [comment]
Go @surajssd, go :+1:

**Comment by surajssd** [comment]
The [Nulecule spec](https://github.com/projectatomic/nulecule/tree/master/spec#container-application-object) defines that the metadata should be optional but looking at the code [here](https://github.com/projectatomic/atomicapp/blob/master/atomicapp/nulecule/base.py#L42) it feels like the implementation is not done in such a way. So do we need to change the way Nulecule object is made by making `metadata` parameter a keyword parameter or should we make a workaround by keeping the definition as it is?(I do have a working, workaround though)

**Comment by rtnpro** [comment]
@surajssd The Nulecule SPEC is correct. We need to fix the implementation of ``metadata`` in atomicapp. So, [here](https://github.com/projectatomic/atomicapp/blob/master/atomicapp/nulecule/base.py#L42), we can move ``metadata`` as a keyword argument with ``None`` as default. And in the ``__init__`` method, we do something like:
```
self.metadata = metadata or {}
```
so that we have a dictionary for any subsequent use of ``metadata``.

I hope that this helps.

**Comment by surajssd** [comment]
@rtnpro yes makes sense, also the way it is called from [`load_from_path`](https://github.com/projectatomic/atomicapp/blob/master/atomicapp/nulecule/base.py#L131) it will not break things also. So yeah just wanted to know if we change the definition there is no harm done.

**Comment by rtnpro** [comment]
Cool, then you are good to go @surajssd :)

**Comment by dustymabe** [comment]
closing #502 via #547
