### ISSUE TITLE
Why `artifact in objects` for OpenShift provider?

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#514]
Just wondering, what is the point for:

```py
           for artifact in objects:
                namespace = self._get_namespace(artifact)
                url = self._get_url(namespace, kind)

                if self.dryrun:
                    logger.info("DRY-RUN: %s", url)
                    continue
                self.oc.deploy(url, artifact)
```

Is the reason why it's looping through objects due to if someone were to define (for exapmle) a ReplicationController as well as a Pod in the same .yaml file?

**Comment by cdrage** [comment]
Isn't the main use case / what people usually do is define one on each .yaml file? Rather than an all-in-one?

**Comment by dustymabe** [comment]
> Isn't the main use case / what people usually do is define one on each .yaml file? Rather than an all-in-one?

That is typically what we have done in our examples but it isn't necessary. We need to account for this possibility. We'll keep it the way it is unless there is some issue it is causing.

**Comment by dustymabe** [comment]
Should we close this now?

**Comment by dustymabe** [comment]
@cdrage ^^
