### ISSUE TITLE
Create a config class to manage config data

### ISSUE THREAD

**Issue by rtnpro** [projectatomic/atomicapp#524]
As mentioned here: https://github.com/projectatomic/atomicapp/pull/522#issuecomment-172894076, management of config data is becoming convoluted using a dictionary. It'd be best if we create a ``Config`` class which abstracts all operations (loading, resolving of config data) on config data and provides a clean interface to interact with the config data.

**Comment by cdrage** [comment]
Yeahhhh. :+1: for this. Let's get this implemented.

Albit this should be added post-GA as to not incur any bugs introduced before-hand.

**Comment by dustymabe** [comment]
I'd also like to make sure that this config class keeps track of where values are provided from and tracks a hierarchy. i.e. if `namespace` variable exists in answers.conf as well as was provided on the command line via `--namespace`, I'd like the class to keep track of both values as well as the priority. If the command line has higher priority then we should return that one when a calling function asks for the value of namespace.
