### ISSUE TITLE
Move the `Developers` section from README to CONTRIBUTING

### ISSUE THREAD

**Issue by surajssd** [projectatomic/atomicapp#542]
Currently in the documentation of [`README.md`](https://github.com/surajssd/atomicapp/blob/master/README.md) we have [`Developers`](https://github.com/surajssd/atomicapp#developers) section, and again we have [`CONTRIBUTING.md`](https://github.com/surajssd/atomicapp/blob/master/CONTRIBUTING.md) so why not move the [`Developers`](https://github.com/surajssd/atomicapp#developers) section from [`README.md`](https://github.com/surajssd/atomicapp/blob/master/README.md) to [`CONTRIBUTING.md`](https://github.com/surajssd/atomicapp/blob/master/CONTRIBUTING.md) altogether?

**Comment by cdrage** [comment]
Fixed by #576
