### ISSUE TITLE
What's application-entity?

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#573]
My google-fu and search skills seem to not be very strong. (I've searched via the nulecule spec, nulecule-library, atomicapp)

But what is `application-entity` and why do we need it?

It seems much cleaner using:

```
FROM projectatomic/atomicapp
MAINTAINER Your Name <you@example.com>
ADD /Nulecule /Dockerfile /artifacts /README.md
```

**Comment by dustymabe** [comment]
It's just the directory within the image where the Nulecule files exist. Otherwise you are adding the data to the root of the filesystem along with /dev /var /usr etc..

**Comment by cdrage** [comment]
Thanks for clearing that it! Thought we we're using it after `grep -r` the dir for any other instances of it.
