### ISSUE TITLE
Why do atomic apps have a "Dockerfile"?

### ISSUE THREAD

**Issue by jberkus** [projectatomic/atomicapp#578]
One thing which really confused me about each atomicapp folder was the presence of a "Dockerfile".  The reason this is confusing is that, in Docker, Dockerfiles are used to *build* images and not run them.  But atomicapp only runs images ... it doesn't build them.   And, for that matter, the "Dockerfile" always seems to have the same contents, except the list of providers changes.

So, why does that file even exist?  Why not put the list of providers in the Nulecule file?

**Comment by dustymabe** [comment]
In practice the atomic apps (like the ones in the nulecule-library) are packaged up into a docker image. This is the delivery mechanism. So the Dockerfile exists to take the Nulecule and the artifacts and add them to the Atomic App software base image. Then one can start an Atomic App using Atomic CLI pretty easily (`atomic run projectatomic/helloapache`) without having to actually have the Atomic App software installed on the system (it runs from inside the container).

**Comment by jberkus** [comment]
Note added to new getting started guide PR.  Closing ....
