### ISSUE TITLE
Warn the user instead of error out on persistent storage.

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#586]
When using persistent storage with the Docker or OpenShift provider this error appears:

```
ERROR:atomicapp:Requirement persistent_storage does not exist
```

Instead, `atomicapp` should warn the user instead of erroring out.

**Comment by dustymabe** [comment]
looks like #584. Is that correct?

**Comment by cdrage** [comment]
Yeah.. I'll close this one in favour of #584
