### ISSUE TITLE
ReadWrite no longer a parameter for Persistent Storage.

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#587]
http://www.projectatomic.io/blog/2016/01/atomic-app-0-3-1/ and docs need to be updated.

This will be fixed by #576 for the README.md, incoming PR for atomic-site.

Basically, we implemented persistent storage before kubernetes hit 1.0.0 and thus the API changed before release.

ReadWriteOnce, ReadOnlyMany, ReadWriteMany are the new options.

**Comment by jberkus** [comment]
Do those names also work with Marathon?  How do we interpret them for Docker?

**Comment by cdrage** [comment]
@jberkus 

Unfortunately just Kubernetes is supported at the moment :( the docs will be updated soon with the information about it.

**Comment by jberkus** [comment]
My point is, we shouldn't be using provider-specific names in Nulecule files.

**Comment by goern** [comment]
ReadWriteOnce, ReadOnlyMany, ReadWriteMany these words seem to nail the desired behavior of the persistent volume pretty well, I would consider them as 'common sense and meaningful' rather than 'provider specific names'.

**Comment by jberkus** [comment]
Ok.  In that case, though, we'll want to have plans for how those will map to other providers.

**Comment by dustymabe** [comment]
@cdrage - there are also several tests that mention 'ReadWrite':

./tests/units/persistent_storage/test_ps.py
./tests/units/persistent_storage/test_examples/ps-helloapache/Nulecule

**Comment by cdrage** [comment]
Closing as #610 #611 has fixed this. Plus the update to the docs
