### ISSUE TITLE
make providers configurable

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#59]
As a deployer,
I want to configure a provider to use a provider specific configuration file
so that I can deploy remotely to a kubernetes or openshift cluster.

**Comment by goern** [comment]
same pattern needs to be applied to an openshift provider

**Comment by aweiteka** [comment]
Closely related (dupe?) #75

**Comment by goern** [comment]
ja, seems to be a generalization of #75

**Comment by dustymabe** [comment]
@goern should we close in favor of https://github.com/projectatomic/atomicapp/issues/75

**Comment by goern** [comment]
@vpavlin ping?

**Comment by vpavlin** [comment]
This is fixed by https://github.com/projectatomic/atomicapp/pull/267
