### ISSUE TITLE
Do not trigger Travis CI on documentation PRs

### ISSUE THREAD

**Issue by surajssd** [projectatomic/atomicapp#605]
For documentation PRs it is not necessary to trigger a travis CI

**Comment by surajssd** [comment]
We can skip a Travis CI build just by adding `[ci skip]` to a commit message. 

Source: https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build
We need to document this in [`CONTRIBUTING.md`](https://github.com/projectatomic/atomicapp/blob/master/CONTRIBUTING.md)

**Comment by dustymabe** [comment]
The only undesirable part of this is that [ci skip] (which is unrelated to the change that was made) is now scattered throughout our git history. Not a big, deal, but something to think about.

**Comment by dustymabe** [comment]
Is it possible to configure travis to ignore docs PR some other way?

**Comment by surajssd** [comment]
@dustymabe we can keep this open until we find some other way!

**Comment by dustymabe** [comment]
I'm fine with closing this issue - It would be nice to have a different way to achieve this goal but I actually don't see it as something we need to focus on. It doesn't hurt much to have the tests run and they run pretty quick, so not a big deal.
