### ISSUE TITLE
Global params for nulecule

### ISSUE THREAD

**Issue by whitel** [projectatomic/atomicapp#61]
So, I have a nulecule that has a mariadb and a drupal, they both need a couple of the same params (e.g. db_user). Currently, my nulecule looks like this (trimmed some for brevity):
    
        specversion: 0.0.1-alpha
        id: drupal-app
        metadata:
           name: Drupal App
           appversion: 0.0.1
           description: This is a Drupal Atomicapp
        graph:
           drupal:
              params:
                 db_user:
                    description: database user
              artifacts:
                 kubernetes:
                    - file://graph/k8s/drupal-pod.json
                    - file://graph/k8s/drupal-service.json
           mariadb-app:
              source: docker://localhost:5000/mariadb-app
              params:
                 db_user:
                    description: database user

But, I think I want some way to do this:

        specversion: 0.0.1-alpha
        id: drupal-app
        metadata:
           name: Drupal App
           appversion: 0.0.1
           description: This is a Drupal Atomicapp
        params:
            db_user:
                description: database user
        graph:
           drupal:
              artifacts:
                 kubernetes:
                    - file://graph/k8s/drupal-pod.json
                    - file://graph/k8s/drupal-service.json
           mariadb-app:
              source: docker://localhost:5000/mariadb-app`

and have the param pass through to both. However, this also raises the issue of "namespacing the param".

**Comment by goern** [comment]
what about
```
graph:
  _global:
    db_user:
      description: db user
  mariadb-atomicapp:
    source: ....
```

That is covered by Nulecule 0.0.2 and is implementing a specific behavior of atomicapp.

**Comment by vpavlin** [comment]
How is that covered by 0.0.2? I don't see anything like that in a spec

**Comment by goern** [comment]
This will be covered by the 'xpath params epic'
