### ISSUE TITLE
We need an implementation of Nulecule's Storage Requirements

### ISSUE THREAD

**Issue by veillard** [projectatomic/atomicapp#62]
Needed for all those examples around databases etc ...
Spec v2 is at
 https://github.com/projectatomic/nulecule/tree/master/spec/0.0.2#storage-requirements-object

**Comment by vpavlin** [comment]
Looking at https://github.com/projectatomic/nulecule/tree/master/spec#storageRequirementsObject I am not sure how do we translate this to a real storage. Any more detailed explanation on how to implement this feature?

**Comment by goern** [comment]
storageRequirements correspond to [Persistent Storage in Kubernetes](https://github.com/GoogleCloudPlatform/kubernetes/blob/release-1.0/docs/design/persistent-storage.md) two steps need to be performed:

0. the application packager has a [storage requirement](https://github.com/GoogleCloudPlatform/kubernetes/blob/release-1.0/docs/design/persistent-storage.md#users-request-storage), this must be translated to a persistant storage claim object to be deployed to kubernetes or openshift3
1. the deployment guy needs to [provision storage](https://github.com/GoogleCloudPlatform/kubernetes/blob/release-1.0/docs/design/persistent-storage.md#admin-provisions-storage) (within kube or openshift) without this, 0. will lead to a blocked deployment of the application

step 1. is implemented either as a) part of `answers.conf` or b) a kube config that is dropped in the correct artifacts directory.

I would vote for a) which also means that we need to generate a PersistentVolume object and deploy it during `atomic run`. 

AFAIK there is no need to respect any sequence of deployment.

**Comment by kanarip** [comment]
[OpenShift specifies an attribute "volumeMounts"](https://github.com/projectatomic/atomicapp/blob/master/tests/units/cli/test_examples/wordpress-centos7-atomicapp/artifacts/openshift/pod.yaml#L25) to a container, which seems very much like what we need.

**Comment by goern** [comment]
ja, OpenShift (more precisely Kubernetes) has a two fold concept:
1. there is a Persistent Volume Claim, that claim is issued by the application and can be generated out of a Nulecule file by atomicapp's openshift provider
2. that claim must be satisfied by a Persistent Volume, which is configured/provisioned by the platform administrator

Both must match, so a claim for 512Mi will be satisfied by a volume of 512Mi...

Further info: https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/design/persistent-storage.md

**Comment by dustymabe** [comment]
We just merged persistent storage for kubernetes in #460. Closing.
