### ISSUE TITLE
Replace all the file with copyright 2015 to 2016

### ISSUE THREAD

**Issue by surajssd** [projectatomic/atomicapp#635]
Still some files have copyright notice with year 2015 in them, so we should change it to 2016.

**Comment by surajssd** [comment]
@Preeticp would you want to work on this?

**Comment by pnemade** [comment]
AFAIK, we should keep all the years for copyright in the source code. See https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html

**Comment by surajssd** [comment]
@pnemade yes whatever is the right way to go! I said replace because [some of the docs](https://github.com/projectatomic/atomicapp/pull/535/files#diff-04c6e90faac2675aa89e2176d2eec7d8R86) have year replaced with 2016.

**Comment by jberkus** [comment]
Standard way is to have a range, e.g.: copyright 2014-2016

**Comment by cdrage** [comment]
@surajssd can you make a PR for this :)

**Comment by surajssd** [comment]
@cdrage I thought @Preeticp is working on this!

**Comment by Preeticp** [comment]
@cdrage I am working on this.

**Comment by cdrage** [comment]
Fixed by #651
