### ISSUE TITLE
Add new labels for helping beginners

### ISSUE THREAD

**Issue by surajssd** [projectatomic/atomicapp#648]
Add labels like `beginner-friendly`, `documentation`, `low-hanging-fruit`.

**Comment by surajssd** [comment]
@cdrage can you help me with this?

**Comment by cdrage** [comment]
Ah sorry, I don't actually have permission to add labels. @goern @aweiteka ?

**Comment by cdrage** [comment]
Woops! Looks like I actually do :)

need_doc is already added, but I've added low-hanging-fruit and beginner-friendly (same colour)!
