### ISSUE TITLE
genanswers should not require root permissions

### ISSUE THREAD

**Issue by jberkus** [projectatomic/atomicapp#652]
The way it is now:

`atomicapp genanswers` requires root permissions to run because of the /var/run lock.  This causes two issues:

* unnecessary use of "sudo" by the user;
* the resulting answers.conf file is owned by root, and thus not editable by the user

The way it should be:

`genanswers` should run with the user's permissions.  It has no need to create a lock, since it does nothing which requires one.

**Comment by goern** [comment]
+1 good catch!



-- 
Principal Software Engineer - Systems Design & Engineering
Mobile: +49 171 2801345

Red Hat GmbH, http://www.de.redhat.com/, Sitz: Grasbrunn,
Handelsregister: Amtsgericht München, HRB 153243,
Geschäftsführer: Paul Argiry, Charles Cachera, Michael Cunningham, Michael
O'Neill

**Comment by TomasTomecek** [comment]
Related: https://github.com/projectatomic/atomicapp/issues/640

**Comment by cdrage** [comment]
/var/run has been removed! Let me know if this has fixed your issue @jberkus

**Comment by jberkus** [comment]
Verified that it's working as expected.
