### ISSUE TITLE
Add default config value ~/.kube/config for both OpenShift and Kubernetes.

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#656]
ping @kadel @dustymabe @rtnpro 

So currently we use `kubectl` got Kubernetes. This automatically picks up `.kube/config` for usage.

We do NOT do this with OpenShift as we have to manually specify --providerconfig or  token + ca.

Thus you can easily run `atomicapp run --provider=kubernetes foobar`. But with OpenShift you have to provider `atomicapp run --provider=openshift foobar --providerconfig ~/.kube/config`.

With the conversion of the k8s provider from cmd to api, we have to require a config file location.

Allso, after looking at the OpenShift code we should provide a **DEFAULT** value of `~/.kube/config` of the current user for both the OpenShift and k8s providers. So we no longer have to provider `--providerconfig ~/.kube/config` each time.

Or else we'll break a lot of current blog posts and examples. Also the fact that `~/.kube/config` is conventionally where the user stores their config.

**Comment by cdrage** [comment]
Added the label blocker due to the nature of all these examples / blog posts we currently have.

I don't like the feeling of having to add `--providerconfig ~/.kube/config` to each `atomicapp run projectatomic/helloapache`.

**Comment by dustymabe** [comment]
@cdrage - I agree that picking up ~/.kube/config is what we should do - see my comment https://github.com/projectatomic/atomicapp/pull/420#issuecomment-163036234

One problem I think is that `~` doesn't work inside the container so what we need to do is actually find out what the user's home directory is and then use the full path right?

**Comment by dustymabe** [comment]
@kadel your input on this would would be appreciated.

**Comment by kadel** [comment]
I agree with defaulting to `~/kube/config`, but as @dustymabe  mentioned finding users home directory might be tricky.

I don't know if there is a easy way how to find out what who started container :-( 
There is `$SUDO_UID` in atomic cli (https://github.com/projectatomic/atomic/blob/master/docs/atomic-run.1.md) but I'm not sure if it is going to be helpful, or how to do this without atomic cli.

**Comment by cdrage** [comment]
@dustymabe @kadel 

We can use the env variables SUDO_USER and USER within atomicapp.

For ex.

If root is ran these are the env variables:
USER=root
SUDO_USER=foobar

If user ran without root:
USER=foobar
SUDO_USER=None

Should be easy to parse :)

**Comment by dustymabe** [comment]
Just be careful here. We can't fully infer the home directory just from the username as your home can be set to other locations. We would need to parse `/etc/passwd` for this.. but then again what about if their information comes from directory services etc.. We might be able to get the $HOME env var from atomic cli and pass it through? 

All i'm trying to say is let's make sure we cover the angles.

**Comment by cdrage** [comment]
@dustymabe You're right, we need to cover all angles on this when we decide to implement.

**Comment by rtnpro** [comment]
@dustymabe 

The ``$HOME`` env variable does not work for ``sudo``, it points to ``/root`` instead of the user's home dir.

**Comment by cdrage** [comment]
@rtnpro See https://github.com/projectatomic/atomicapp/pull/658 I believe we've fixed this now.

This will be unblocked once https://github.com/projectatomic/atomicapp/pull/658 is merged in and then we add default configuration to Kubernetes && OpenShift providers.
