### ISSUE TITLE
typing only `atomicapp` should display help

### ISSUE THREAD

**Issue by containscafeine** [projectatomic/atomicapp#668]
When we type only the command `atomicapp`, we do not get the help as output. Will it be better if we get the help printed on screen?
Thoughts?

**Comment by abhi1004** [comment]
@containscafeine I'll look into the issue.

**Comment by containscafeine** [comment]
@abhi1004 Oh, sure, thanks!
@surajssd @cdrage @dustymabe @rtnpro does this behavior makes sense?

**Comment by surajssd** [comment]
@containscafeine yes it does

**Comment by containscafeine** [comment]
Closing, fixed in #756!
