### ISSUE TITLE
docker-inspect error when no containers running on system

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/atomicapp#672]
There is a docker inspect error when there are not yet any containers running on the system:

```
[INFO] - docker.py - Deploying to provider: Docker
docker: "inspect" requires a minimum of 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] CONTAINER|IMAGE [CONTAINER|IMAGE...]

Return low-level information on a container or image
```

This comes from the following line in docker.py: 
```
docker_cmd = 'docker inspect --format="{{ .Name }}" $(docker ps -aq --no-trunc) | sed "s,/,,g"'
```

We need to run the docker ps command first and then only if there are existing containers running will we call docker-inspect.

**Comment by dustymabe** [comment]
This is most likely a new error resulting from move to docker 1.9 on host.

**Comment by dustymabe** [comment]
@containscafeine can you take this one?

**Comment by containscafeine** [comment]
@dustymabe taken! :)

**Comment by containscafeine** [comment]
@dustymabe is it fine if we use
`docker ps -a --format="{{ .Names }}"`
instead of
`docker inspect --format="{{ .Name }}" $(docker ps -aq --no-trunc) | sed "s,/,,g"`
or is there a reason that we are using `docker inspect`?

**Comment by dustymabe** [comment]
@containscafeine much better! I had tried to do the same thing but I was trying to use `"{{ .Name }}" and it was giving me an error. `.Names` is great!
