### ISSUE TITLE
sudo atomic run $image yields empty `-v` argument

### ISSUE THREAD

**Issue by jasonbrooks** [projectatomic/atomicapp#673]
On centos with `atomic-1.9-4.gitff44c6a.el7.x86_64`, the command `sudo atomic run projectatomic/guestbookgo-atomicapp` produces the command `docker run -it --rm --privileged -v -v /run:/run -v /:/host --net=host --name guestbookgo-atomicapp -e NAME=guestbookgo-atomicapp -e IMAGE=projectatomic/guestbookgo-atomicapp projectatomic/guestbookgo-atomicapp run`. 

The blank `-v` leads to the error `invalid value "-v" for flag -v: -v is not an absolute path`.

Adding `-E` to sudo, or running as root w/o sudo, provides the correct command line. 

see also http://fpaste.org/349631/17452145/

cc @dustymabe

**Comment by dustymabe** [comment]
This is an issue in Atomic CLI that was fixed. Unfortunately the version in RHEL/CentOS don't have the new commit in it so we'll have to wait for the next release. 

https://github.com/projectatomic/atomic/issues/339

**Comment by surajssd** [comment]
@dustymabe we can still `yum update` right?

**Comment by dustymabe** [comment]
> @dustymabe we can still yum update right?

@surajssd not if there isn't a newer atomic cli package available. What I am saying is that we have to wait until there is a new release of the atomic cli package before this will be fixed.

**Comment by surajssd** [comment]
okay, sure

**Comment by dustymabe** [comment]
see https://github.com/projectatomic/atomic/issues/339#issuecomment-232637366 - atomic 1.10 is available now which is the answer to this problem. We should close this.
