### ISSUE TITLE
Changing $image answer does not re-pull 

### ISSUE THREAD

**Issue by whitel** [projectatomic/atomicapp#68]
I believe, that if I change the "answer" for an image param in the nulecule, atomicapp does not get the "new" image it uses the one it pulled based on install.

**Comment by goern** [comment]
could you give us some more log? like before and after changing the image

**Comment by vpavlin** [comment]
Atomicapp does not pull images specified by params - that's kubes jobs. The only thing atomicapp does is templating and submitting kube files. PR https://github.com/projectatomic/atomicapp/pull/85 will let you review templated files after the run, maybe that will help.

**Comment by whitel** [comment]
I think I was not getting new, gen'd files when I changed the $image value in the answers file post first run. I will retest when I get a chance later today.

**Comment by aweiteka** [comment]
@whitel if there's no reproducer can we close this?

**Comment by whitel** [comment]
Sure, might have been a "point in time" bug anyway. We can just see if it crops up again. Just keep an eye out for "if answers file changes, do the newly gen'd kube files reflect the change, particularly for $image"
