### ISSUE TITLE
Should we deprecate locking?

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#704]
#599 

Should we deprecate logging in favour of having Atomic App providers determining whether the application has been deployed or not?

**Comment by cdrage** [comment]
Would clear up:
#598
#498 
#497 
#496

**Comment by dustymabe** [comment]
I think this is a decent idea for now. It's causing enough issues to inhibit some users. I say we remove it and then surgically add it back when concurrency becomes an issue.

**Comment by surajssd** [comment]
+1 for removing the locking right now, because it has added unnecessary complexity in many places!

**Comment by cdrage** [comment]
I agree with all above. This blocks in regards to doing tests and such and at the moment Kubernetes / OpenShift / Docker fails if the deploy is ran again (same namespace for k8s + oc, for docker is fails on same docker name, etc.)

**Comment by cdrage** [comment]
Since #706 is merged this issue is now closed
