### ISSUE TITLE
Removing Coverage?

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#728]
I've noticed recently that Coverage has been slow lately as well as not doing the PR's correctly (if you look, you see that most are yellow-coloured.

Vote to remove it in favour of manually checking the code-coverage?

**Comment by kadel** [comment]
Does anyone know what is wrong with it?
I think that it would be great to fix it.

**Comment by cdrage** [comment]
I fixed this by adding `--cov atomicapp` to the tests which previously weren't there
