### ISSUE TITLE
Hyperlink "CLI doc" - page not found

### ISSUE THREAD

**Issue by amitkrout** [projectatomic/atomicapp#741]
While clicking on the hyper link ```CLI doc``` in Basic commands of  ```atomicapp/docs/start_guide.md``` (https://github.com/projectatomic/atomicapp/blob/master/docs/start_guide.md) its redirecting to  - "404 This is not the web page you are looking for"

**Comment by cdrage** [comment]
Good eye! This is fixed in https://github.com/projectatomic/atomicapp/pull/742
