### ISSUE TITLE
When fetching via atomicapp, should set to current user uid/guid

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#745]
Possibly use: http://stackoverflow.com/questions/5994840/how-to-change-the-user-and-group-permissions-for-a-directory-by-name to achieve this.

But at the moment, whenever you fetch an `atomicapp`. It is pulled via sudo and thus all files are chown'd to root.

Should we implement a function that sets the guid/uid of the file pulled to the current user?

**Comment by abhi1004** [comment]
@cdrage Can I work on this, looked into it think I can fix it.

**Comment by cdrage** [comment]
@abhi1004 sorry! funny enough I was *just* putting up a PR for this, should be up in the next hour :)

**Comment by abhi1004** [comment]
Haha okay .

**Comment by cdrage** [comment]
Closed via #772
