### ISSUE TITLE
error when deleting containers in 0.6.2

### ISSUE THREAD

**Issue by jberkus** [projectatomic/atomicapp#794]
Using the Nulecule config I have for projectatomic/atomic-site, I used to auto-delete the container when I stopped testing the site updates.  However, as of AtomicApp 0.6.2, this no longer works:

```
Error deleting container: Error response from daemon: Conflict, You cannot remove a running conta
iner. Stop the container before attempting removal or use -f
```

Under 0.5.X, this worked fine.  Did something change in the order of shutdown?  Or is this an issue with docker?

**Comment by cdrage** [comment]
@jberkus hmmm, shouldn't have, mind doing it with the `-v` command so we can get some verbose logging info?

**Comment by jberkus** [comment]
-v didn't result in any additional output.

```
josh ~/git/redhat/atomic-site-master (giuseppe-intro-system-containers) $ Error deleting container: Error response from daemon: Conflict, You cannot remove a running container. Stop the container before attempting removal or use -f
write /dev/stdout: broken pipe
```

**Comment by jberkus** [comment]
So, after some testing this is a bug in Docker itself.  As a result, closing here.
