### ISSUE TITLE
[provider-openshift] figure out how to get openshift credentials inside the atomicapp

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#8]
given a openshift provider, we need to have credentials to talk to the openshift environment, these need to be accessible to the atomicapp container that is trying to install ... 

Use Case:
As a deployment guy who wants to deploy a "container-app compliant" application,
I want to be able to 'atomic install atomicapp-mongodb'
so that a mongoDB pod is up and running on my OpenShift Enterprise 3 environment

**Comment by aweiteka** [comment]
Implementation approach one is to simply use the openshift client on the host.

**Comment by goern** [comment]
done by using openshift client config file and point to it using `answers.conf`
