### ISSUE TITLE
Unmaintained / Archive

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#807]
@jzb @kadel @aweiteka

We should archive (using the new GitHub feature) and add an [UNMAINTAINED] message to https://github.com/projectatomic/atomicapp

**Comment by jzb** [comment]
I agree - but will leave that to @aweiteka to make final call.

**Comment by jzb** [comment]
Sorry, didn't mean to close!

**Comment by aweiteka** [comment]
ACK. Repo description updated.
