### ISSUE TITLE
Inconsistent dry-run behavior

### ISSUE THREAD

**Issue by tkdchen** [projectatomic/atomicapp#84]
Currently, there are several different behaviors of dry-run. When dry-run is enabled, some of them print a message to stdout by `print` function, some of them output a message by logger, and some of them do not output anything.

When dry-run is enabled, each time encounter dry-run option, a message should be outputted.

IMO, `logger.info` is a good way to output such a dry-run message, which is prefixed with "DRY-RUN: " that is useful to separate dry-run message from normal log messages.

**Comment by vpavlin** [comment]
I agree, it's a mess and it is on my todo to clean up  all log messages. Would you care to send a PR to fix this issue?

**Comment by tkdchen** [comment]
Sure.

**Comment by goern** [comment]
@tkdchen you think you can send the PR till the end of week?

**Comment by tkdchen** [comment]
Yes, I think so.
