### ISSUE TITLE
hardcoded SCHEMA_URL

### ISSUE THREAD

**Issue by tkdchen** [projectatomic/atomicapp#91]
In `create.py`, `SCHEMA_URL` is hardcoded to https://raw.githubusercontent.com/projectatomic/nulecule/master/spec/0.0.1-alpha/schema.json . When user does not provide a schema via `--schema` from command line, a `schema.json` file will be downloaded from that URL. Is this an expected behavior?

There is already a new version 0.0.2 of `schema.json` in `spec/`, should this URL be changed to that new one?

**Comment by goern** [comment]
it should be relocated to something close to https://github.com/projectatomic/atomicapp/blob/master/atomicapp/constants.py#L4

**Comment by vpavlin** [comment]
Well..it is in my local branch...
