### ISSUE TITLE
logger is undefined an a few places

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#94]
In the following location the logger seems to be undefined?!
 * atomicapp/cli/main.py Line 95
 * atomicapp/params.py Line 69
 * atomicapp/params.py Line 111
 * atomicapp/plugin.py Line 33

**Comment by vpavlin** [comment]
Has this been fixed by #97 ?

**Comment by goern** [comment]
yeah, in #97 merge message, you can put something like 'closes/fixes #94' so github will do the linking and closing...
