### ISSUE TITLE
Provider.init should raise NotImplemented error instead of logging a warning message

### ISSUE THREAD

**Issue by tkdchen** [projectatomic/atomicapp#98]
`init` is defined in the base class `Provider`, that must be implemented in each subclass inherited from `Provider`. It should raise NotImplemented error instead of logging a warning message.

**Comment by vpavlin** [comment]
The `init` function is not mandatory, it's just up to provider if it needs to do something specific prior to `deploy` function..although I admit that there is no provider which would skip the implementation of it...
